/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Posttest4;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Gidion
 */
public class Posttest4 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan4
     */
    public Posttest4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nama = new javax.swing.JLabel();
        notelpon = new javax.swing.JLabel();
        berat = new javax.swing.JLabel();
        aturdiskon = new javax.swing.JLabel();
        jenisjs = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtTotal = new javax.swing.JTextField();
        js1 = new javax.swing.JRadioButton();
        JS2 = new javax.swing.JRadioButton();
        slider = new javax.swing.JSlider();
        ad = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtTelpon = new javax.swing.JTextField();
        txtBerat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ulangi = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Struk = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        Proses = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setText("Nama :");

        notelpon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        notelpon.setForeground(new java.awt.Color(255, 255, 255));
        notelpon.setText("No. Telpon :");

        berat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        berat.setForeground(new java.awt.Color(255, 255, 255));
        berat.setText("Berat Barang :");

        aturdiskon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aturdiskon.setForeground(new java.awt.Color(255, 255, 255));
        aturdiskon.setText("Atur Diskon :");

        jenisjs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jenisjs.setForeground(new java.awt.Color(255, 255, 255));
        jenisjs.setText("Jenis Jasa :");

        harga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        harga.setForeground(new java.awt.Color(255, 255, 255));
        harga.setText("Total Harga  :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama)
                    .addComponent(notelpon)
                    .addComponent(berat)
                    .addComponent(aturdiskon)
                    .addComponent(jenisjs)
                    .addComponent(harga))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nama)
                .addGap(31, 31, 31)
                .addComponent(notelpon)
                .addGap(42, 42, 42)
                .addComponent(berat)
                .addGap(45, 45, 45)
                .addComponent(aturdiskon)
                .addGap(38, 38, 38)
                .addComponent(jenisjs)
                .addGap(32, 32, 32)
                .addComponent(harga)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal.setText("Rp.");

        buttonGroup1.add(js1);
        js1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        js1.setText("Reguler");

        buttonGroup1.add(JS2);
        JS2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JS2.setText("Express");

        slider.setBackground(new java.awt.Color(153, 153, 153));
        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });

        ad.setText("0");

        txtNama.setText("Masukkan Nama Anda");
        txtNama.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNamaCaretUpdate(evt);
            }
        });

        txtTelpon.setText("No. Telpon");
        txtTelpon.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTelponCaretUpdate(evt);
            }
        });
        txtTelpon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelponKeyPressed(evt);
            }
        });

        txtBerat.setText("0");
        txtBerat.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBeratCaretUpdate(evt);
            }
        });
        txtBerat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBeratKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kg");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(js1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JS2)
                        .addGap(98, 98, 98))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JS2)
                            .addComponent(js1))
                        .addGap(105, 105, 105))))
        );

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEM INFORMASI PENJUALAN BARANG DAN JASA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MULAWARMANESIA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel3)
                .addContainerGap(243, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(123, 123, 123))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        Ulangi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ulangi.setText("Reset");
        Ulangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UlangiActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        Struk.setEditable(false);
        Struk.setColumns(20);
        Struk.setRows(5);
        jScrollPane1.setViewportView(Struk);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("STRUK");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Proses.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Proses.setText("Proses");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });

        Keluar.setBackground(new java.awt.Color(51, 153, 0));
        Keluar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Keluar.setText("Exit");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(Proses)
                .addGap(53, 53, 53)
                .addComponent(Ulangi)
                .addGap(51, 51, 51)
                .addComponent(Keluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ulangi)
                    .addComponent(Proses)
                    .addComponent(Keluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    String jenis;
//    Float Diskon,Total, Uang;
   
    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        // TODO add your handling code here
        float Diskon, Reguler=11500, Total=0, berat, aturdiskon;
        String nama,notelpon, jenisjs;
        
        
        nama = txtNama.getText();
        notelpon = txtTelpon.getText();
        berat = Float.parseFloat(txtBerat.getText());
        Diskon = Float.valueOf(slider.getValue());        
                
        if (js1.isSelected()){
            jenisjs = js1.getText();
            aturdiskon = Reguler * (Diskon/100)* berat;
            Total = (Reguler * berat)- aturdiskon;
           //F.Total(Total);
        }
        else if (JS2.isSelected()){
            jenisjs = JS2.getText();
            aturdiskon = (float) (Reguler * 1.5 * (Diskon/100)* berat);
            Total = (float)(Reguler * berat * 1.5)- aturdiskon;
        }
        else {
            JOptionPane.showMessageDialog(null, "Pilih Jenis Jasa Terlebih Dahulu","WARNING", JOptionPane.INFORMATION_MESSAGE);
                return;
        }
        txtTotal.setText(""+Total);
        Struk.setText("************STRUK PEMBAYARAN************\n"
                + " Nama\t : "+nama+
                " \n No. Telpon\t : "+notelpon+
                " \n Berat Barang\t : "+berat+
                " \n Diskon\t : "+Total+
                " \n Jenis Jasa\t : "+jenisjs+
                " \n Total Harga\t : Rp."+Total);
    }//GEN-LAST:event_ProsesActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_KeluarActionPerformed

    private void UlangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UlangiActionPerformed
        // TODO add your handling code here:
        txtNama.setText("");
        txtTelpon.setText("");
        txtBerat.setText("");
        txtTotal.setText("");
        buttonGroup1.clearSelection();
        slider.setValue(0);
    }//GEN-LAST:event_UlangiActionPerformed

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
        // TODO add your handling code here:
        ad.setText(String.valueOf(slider.getValue())+"%");
    }//GEN-LAST:event_sliderStateChanged

    private void txtNamaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNamaCaretUpdate
//        // TODO add your handling code here:
//        if (txtNama.getText().length() !=0 && txtTelpon.getText().length() !=0 && txtBerat.getText().length() !=0 && txtBerat.getText().equalsIgnoreCase("0")){
//           Proses.setEnabled(true);}
//        else{
//            
//            Proses.setEnabled(false);}
            if (txtNama.getText().length()==0 || txtBerat.getText().equals("0")){
                Proses.setEnabled(false);
            }
            else if (txtNama.getText().length() !=0 && txtTelpon.getText().length() !=0 && txtBerat.getText().length()!=0){
                Proses.setEnabled(true);
            }
    }//GEN-LAST:event_txtNamaCaretUpdate

    private void txtTelponCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTelponCaretUpdate
        // TODO add your handling code here:
//        if (txtNama.getText().length() !=0 && txtTelpon.getText().length() !=0 && txtBerat.getText().length() !=0 && txtBerat.getText().equalsIgnoreCase("0")){
//           Proses.setEnabled(true);}
//        else{
//            
//            Proses.setEnabled(false);}
        if (txtTelpon.getText().length()==0 || txtBerat.getText().equals("0")){
                Proses.setEnabled(false);
            }
            else if (txtNama.getText().length() !=0 && txtTelpon.getText().length() !=0 && txtBerat.getText().length()!=0){
                Proses.setEnabled(true);

            }
    }//GEN-LAST:event_txtTelponCaretUpdate

    private void txtBeratCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBeratCaretUpdate
        // TODO add your handling code here:
//        if (txtNama.getText().length() !=0 && txtTelpon.getText().length() !=0 && txtBerat.getText().length() !=0 && txtBerat.getText().equals("0")){
//           Proses.setEnabled(true);}
//        else{
//            
//            Proses.setEnabled(false);}
//        
        if (txtBerat.getText().length()==0 || txtBerat.getText().equals("0")){
                Proses.setEnabled(false);
            }
            else if (txtNama.getText().length() !=0 && txtTelpon.getText().length() !=0 && txtBerat.getText().length()!=0){
                Proses.setEnabled(true);
            }         
        
    }//GEN-LAST:event_txtBeratCaretUpdate

    private void txtTelponKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelponKeyPressed
        // TODO add your handling code here:
        txtTelpon.addKeyListener (new KeyAdapter(){
                public void keyTyped(KeyEvent e){
                    char karakter1 = e.getKeyChar();
                    if (!((karakter1 >= '0') && (karakter1 <= '9')) || (karakter1 == '\b')){
                    e.consume();
                }
                }
                });
        
    }//GEN-LAST:event_txtTelponKeyPressed

    private void txtBeratKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBeratKeyPressed
        // TODO add your handling code here:
        txtBerat.addKeyListener (new KeyAdapter(){
                public void keyTyped(KeyEvent e){
                    char karakter1 = e.getKeyChar();
                    if (((karakter1 < '0')||(karakter1 > '9'))&&(karakter1 != '.')){
                    e.consume();
                }
                }
                });
    }//GEN-LAST:event_txtBeratKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtNama.setText("");
        txtTelpon.setText("");
        txtBerat.setText("");
        txtTotal.setText("");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Posttest4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Posttest4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Posttest4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Posttest4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Posttest4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JS2;
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Proses;
    private javax.swing.JTextArea Struk;
    private javax.swing.JButton Ulangi;
    private javax.swing.JLabel ad;
    private javax.swing.JLabel aturdiskon;
    private javax.swing.JLabel berat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel jenisjs;
    private javax.swing.JRadioButton js1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel notelpon;
    private javax.swing.JSlider slider;
    private javax.swing.JTextField txtBerat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelpon;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
